name: Fly Deploy Dev

on:
  workflow_run:
    workflows: [Lanttern tests]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Get contributor info
        id: contributor
        run: |
          # Get GitHub username (who triggered the workflow)
          GITHUB_USER=$(echo "${{ github.event.workflow_run.triggering_actor.login }}" | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]-')

          echo "github_user=${GITHUB_USER}" >> $GITHUB_OUTPUT
          echo "GitHub User: ${GITHUB_USER}"
          
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
        
      - name: Deploy to contributor's Fly.io app
        run: |
          # Try contributor-specific GitHub username first, then fallback to shared
          flyctl deploy --remote-only ${{ secrets[format('FLY_DEPLOY_OPTS_{0}', steps.contributor.outputs.github_user)] || secrets.FLY_DEPLOY_OPTS }}
        env:
          # Try contributor-specific GitHub username first, then fallback to shared
          FLY_API_TOKEN: ${{ secrets[format('FLY_API_TOKEN_{0}', steps.contributor.outputs.github_user)] || secrets.FLY_API_TOKEN }}
