name: Fly Deploy Dev

on:
  workflow_run:
    workflows: [Lanttern tests]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
